// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_EventType int32

const (
	Event_Creat  Event_EventType = 0
	Event_Update Event_EventType = 1
	Event_Delete Event_EventType = 2
)

var Event_EventType_name = map[int32]string{
	0: "Creat",
	1: "Update",
	2: "Delete",
}

var Event_EventType_value = map[string]int32{
	"Creat":  0,
	"Update": 1,
	"Delete": 2,
}

func (x Event_EventType) String() string {
	return proto.EnumName(Event_EventType_name, int32(x))
}

func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{5, 0}
}

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{0}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResponse struct {
	Update               bool     `protobuf:"varint,1,opt,name=update,proto3" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{1}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

type DeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{2}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteResponse struct {
	Removed              bool     `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{3}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

type Filter struct {
	Create               bool     `protobuf:"varint,1,opt,name=create,proto3" json:"create,omitempty"`
	Update               bool     `protobuf:"varint,2,opt,name=update,proto3" json:"update,omitempty"`
	Delete               bool     `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{4}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

func (m *Filter) GetUpdate() bool {
	if m != nil {
		return m.Update
	}
	return false
}

func (m *Filter) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type Event struct {
	Type                 Event_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Event_EventType" json:"type,omitempty"`
	Key                  string          `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string          `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	OldValue             string          `protobuf:"bytes,4,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{5}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() Event_EventType {
	if m != nil {
		return m.Type
	}
	return Event_Creat
}

func (m *Event) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Event) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Event) GetOldValue() string {
	if m != nil {
		return m.OldValue
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Event_EventType", Event_EventType_name, Event_EventType_value)
	proto.RegisterType((*PutRequest)(nil), "pb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "pb.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*Filter)(nil), "pb.Filter")
	proto.RegisterType((*Event)(nil), "pb.Event")
}

func init() {
	proto.RegisterFile("pb/service.proto", fileDescriptor_6ff5ab49d8a5fcc4)
}

var fileDescriptor_6ff5ab49d8a5fcc4 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x4f, 0xbb, 0x40,
	0x10, 0x2d, 0x50, 0xf8, 0x95, 0xf9, 0xc5, 0x8a, 0xa3, 0x31, 0xa4, 0x5e, 0x74, 0x13, 0x63, 0xe3,
	0x01, 0xb5, 0xfa, 0x0d, 0xfc, 0x73, 0xe9, 0xa5, 0x41, 0xad, 0x47, 0x53, 0xca, 0x24, 0x36, 0x62,
	0x77, 0x85, 0x85, 0x84, 0xef, 0xe0, 0xd7, 0xf0, 0x7b, 0x9a, 0xdd, 0xa5, 0x14, 0x0f, 0x5e, 0x9a,
	0x79, 0xf3, 0x76, 0xde, 0xbc, 0xbe, 0x01, 0x02, 0x91, 0x5c, 0x14, 0x94, 0x57, 0xab, 0x25, 0x45,
	0x22, 0xe7, 0x92, 0xa3, 0x2d, 0x12, 0x76, 0x03, 0x30, 0x2b, 0x65, 0x4c, 0x9f, 0x25, 0x15, 0x12,
	0x03, 0x70, 0xa6, 0x54, 0x87, 0xd6, 0xb1, 0x35, 0xf6, 0x63, 0x55, 0xe2, 0x01, 0xb8, 0xd5, 0x22,
	0x2b, 0x29, 0xb4, 0x75, 0xcf, 0x00, 0x76, 0x0a, 0xff, 0xf5, 0x54, 0x21, 0xf8, 0xba, 0x20, 0x3c,
	0x04, 0xaf, 0x14, 0xe9, 0x42, 0x92, 0x9e, 0x1c, 0xc4, 0x0d, 0x62, 0x27, 0xb0, 0x73, 0x47, 0x19,
	0x49, 0xfa, 0x53, 0x9f, 0x9d, 0xc3, 0x70, 0xf3, 0xa4, 0x11, 0x0b, 0xe1, 0x5f, 0x4e, 0x1f, 0xbc,
	0xa2, 0xb4, 0x51, 0xdb, 0x40, 0x36, 0x03, 0xef, 0x61, 0x95, 0x49, 0xca, 0xd5, 0xc2, 0x65, 0x4e,
	0x9d, 0x85, 0x06, 0x75, 0x8c, 0xd8, 0x5d, 0x23, 0xaa, 0x9f, 0xea, 0x2d, 0xa1, 0x63, 0xfa, 0x06,
	0xb1, 0x6f, 0x0b, 0xdc, 0xfb, 0x8a, 0xd6, 0x12, 0xcf, 0xa0, 0x2f, 0x6b, 0x61, 0xf4, 0x86, 0x93,
	0xfd, 0x48, 0x24, 0x91, 0x26, 0xcc, 0xef, 0x53, 0x2d, 0x28, 0xd6, 0x0f, 0xd4, 0x5f, 0x78, 0xa7,
	0xba, 0x89, 0x43, 0x95, 0xdb, 0x88, 0x9c, 0x4e, 0x44, 0x78, 0x04, 0x3e, 0xcf, 0xd2, 0x57, 0xc3,
	0xf4, 0x35, 0x33, 0xe0, 0x59, 0x3a, 0xd7, 0xf9, 0x45, 0xe0, 0xb7, 0xba, 0xe8, 0x83, 0x7b, 0xab,
	0xec, 0x07, 0x3d, 0x04, 0xf0, 0x9e, 0xb5, 0xe3, 0xc0, 0x52, 0xb5, 0x49, 0x26, 0xb0, 0x27, 0x5f,
	0x16, 0xf8, 0xd3, 0xf9, 0xa3, 0xb9, 0x1e, 0x8e, 0xc1, 0x99, 0x95, 0x12, 0x87, 0xca, 0xe4, 0xf6,
	0x78, 0xa3, 0xdd, 0x16, 0x9b, 0x24, 0x59, 0x0f, 0xaf, 0x36, 0x1a, 0xb8, 0xa7, 0xc8, 0x5f, 0xc7,
	0x18, 0x61, 0xb7, 0xd5, 0x8e, 0x30, 0x70, 0x5f, 0x16, 0x72, 0xf9, 0x86, 0xa0, 0x68, 0x93, 0xf7,
	0xc8, 0x6f, 0xf3, 0x60, 0xbd, 0x4b, 0x2b, 0xf1, 0xf4, 0xf7, 0x73, 0xfd, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xda, 0xe1, 0x6f, 0x4b, 0x53, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KVServiceClient is the client API for KVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KVServiceClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Watch(ctx context.Context, in *Filter, opts ...grpc.CallOption) (KVService_WatchClient, error)
}

type kVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKVServiceClient(cc grpc.ClientConnInterface) KVServiceClient {
	return &kVServiceClient{cc}
}

func (c *kVServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/pb.KVService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.KVService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServiceClient) Watch(ctx context.Context, in *Filter, opts ...grpc.CallOption) (KVService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KVService_serviceDesc.Streams[0], "/pb.KVService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &kVServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KVService_WatchClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type kVServiceWatchClient struct {
	grpc.ClientStream
}

func (x *kVServiceWatchClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KVServiceServer is the server API for KVService service.
type KVServiceServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Watch(*Filter, KVService_WatchServer) error
}

// UnimplementedKVServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKVServiceServer struct {
}

func (*UnimplementedKVServiceServer) Put(ctx context.Context, req *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (*UnimplementedKVServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedKVServiceServer) Watch(req *Filter, srv KVService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterKVServiceServer(s *grpc.Server, srv KVServiceServer) {
	s.RegisterService(&_KVService_serviceDesc, srv)
}

func _KVService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KVService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Filter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVServiceServer).Watch(m, &kVServiceWatchServer{stream})
}

type KVService_WatchServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type kVServiceWatchServer struct {
	grpc.ServerStream
}

func (x *kVServiceWatchServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _KVService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KVService",
	HandlerType: (*KVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _KVService_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KVService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _KVService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/service.proto",
}
